"""Render the shipped aggregate artifacts as documentation tables.  # 2026-09-05

**The docs used to refuse to print a coefficient, and the reason was good.** Six pages carried
their own copy of the EPIC table and all six went stale together the first time the model was
refitted, because nothing read them. So the tables are not written down anywhere -- they are
generated from ``src/mhcmatch/data/aggregate_*.json`` at Sphinx build time (``docs/conf.py``
calls :func:`write`), and the one committed copy, the summary block in ``README.md``, is pinned
by ``tests/test_modeldoc.py``.

Nothing here reads a benchmark file. Every number printed is a field of the artifact that ships,
which is what keeps a *library* page describing the product rather than restating a benchmark.

::

    python -m mhcmatch._modeldoc            # refresh docs/_generated/ and the README block
"""
from __future__ import annotations

import pathlib

from . import rank as R

__all__ = ["ORDER", "summary_rows", "readme_markdown", "model_rst", "summary_rst", "write"]

#: The shipped cells, in the order the documentation reads them: human class I first because it is
#: the fit the manuscript pins, then the three that were added around it, then the second mode.
#:
#: **Keyed by ``(cls, species, mode)``, and it was ``(cls, species)`` until 1.14.0.** ``_art``
#: hardcoded ``"neoantigen"``, so a pathogen artifact would have shipped, scored, and appeared in
#: ``rank.models()`` while every documentation page silently omitted it. That is the one failure
#: mode this module exists to prevent, arriving through the door it left open.
ORDER = [("mhc1", "human", "neoantigen"), ("mhc1", "mouse", "neoantigen"),
         ("mhc2", "human", "neoantigen"), ("mhc2", "mouse", "neoantigen"),
         ("mhc1", "human", "pathogen")]

README_BEGIN = "<!-- BEGIN shipped-models (generated by mhcmatch._modeldoc) -->"
README_END = "<!-- END shipped-models -->"


def _art(cls, species, mode="neoantigen"):
    return R.aggregate(cls, species, mode)


def _fmt(x, nd=4):
    return "--" if x is None else f"{x:,.{nd}f}"


def _pct(fit):
    """Prevalence, at a resolution that survives NCI: 0.18 % and 41.2 % in the same column."""
    v = 100 * fit["positives"] / fit["rows"]
    return f"{v:.1f} %" if v >= 1 else f"{v:.2f} %"


def _p(x):
    """A p-value at three significant figures, switching to exponent notation below 1e-3."""
    if x is None:
        return "--"
    return f"{x:.3g}" if x >= 1e-3 else f"{x:.1e}"


def _at(field, term, i):
    """Read one term's entry from a field the artifact may store as a dict **or** a list.

    Both spellings ship: ``coef`` is keyed by term on some artifacts and positional on others.
    A reader that assumes either one is a reader that works on half the fits.
    """
    if field is None:
        return None
    return field[i] if isinstance(field, list) else field.get(term)


def _headline(a):
    """The one discrimination figure this artifact records, and what it is called.

    The shipped fits do not share a protocol and must not share a column header. Three protocols
    are in play: the human class-I neoantigen fit reports **leave-one-screen-out**, a mean over
    seven screens held out whole; the three single-deposit neoantigen fits report an **in-sample
    within-reference** figure, macro-averaged over the references carrying at least three of each
    class; and `mhc1.human.pathogen`, a whole-corpus GLM with one global intercept, has neither a
    screen to hold out nor a per-reference intercept to exclude and reports **in-sample, pooled off
    the logit**. Naming them apart is the point -- averaged into one column they would read as one
    quantity measured five times.
    """
    fit = a.get("fit") or {}
    if "in_sample_auroc" in fit:
        return "in-sample, within reference", fit["in_sample_auroc"]
    loo = [r for r in (a.get("loo") or []) if r.get("decided")]
    if loo:
        return "leave-one-screen-out, mean", sum(r["auroc"] for r in loo) / len(loo)
    if "auroc" in fit:
        # The pathogen fit is a whole-corpus GLM read off the logit, with no per-reference
        # intercepts to exclude and no screens to hold out -- a THIRD protocol, and it gets its own
        # label for the same reason the other two do: three numbers in one column would be read
        # down as if they were comparable.
        return "in-sample, pooled off the logit", fit["auroc"]
    return "--", None


def summary_rows():
    """One record per shipped fit: identity, what it was fitted on, and its headline AUROC."""
    out = []
    for cls, species, mode in ORDER:
        a = _art(cls, species, mode)
        fit = a.get("fit") or {}
        metric, auroc = _headline(a)
        out.append({
            "model_id": a["model_id"], "version": a["version"], "release": a["release"],
            "terms": len(a["features"]), "rows": fit.get("rows"),
            "positives": fit.get("positives"),
            # A whole-corpus GLM has ONE unpenalised intercept and no grouping unit at all, so
            # `references or screens` renders it "None per screen" -- which reads as a missing
            # field rather than as the design. `fit["intercepts"]` is what such a fit records.
            "intercepts": (fit.get("references") or len(fit.get("screens") or [])
                           or fit.get("intercepts") or None),
            "unit": ("reference" if fit.get("references")
                     else "screen" if fit.get("screens")
                     else "corpus, global"),
            "metric": metric, "auroc": auroc, "bic": fit.get("bic"),
        })
    return out


# --------------------------------------------------------------------------- README

def readme_markdown():
    """The compact four-row table the README carries, between the generated-block markers."""
    head = ("| `model_id` | model version | release | terms | rows | positives | intercepts "
            "| AUROC | how that AUROC is measured |\n"
            "|---|--:|---|--:|--:|--:|--:|--:|---|")
    lines = [head]
    for r in summary_rows():
        lines.append(
            f"| `{r['model_id']}` | **{r['version']}** | {r['release']} | {r['terms']} "
            f"| {r['rows']:,} | {r['positives']:,} | {r['intercepts']} per {r['unit']} "
            f"| **{_fmt(r['auroc'])}** | {r['metric']} |")
    return "\n".join(lines)


# --------------------------------------------------------------------------- reST

def _list_table(title, headers, rows, widths=None):
    w = widths or [max(8, 60 // len(headers))] * len(headers)
    out = [f".. list-table:: {title}", f"   :header-rows: {1 if headers else 0}",
           "   :widths: " + " ".join(str(x) for x in w), ""]
    for row in ([headers] if headers else []) + rows:
        out.append(f"   * - {row[0]}".rstrip())
        out.extend(f"     - {c}".rstrip() for c in row[1:])
    out.append("")
    return out


def summary_rst():
    rows = [[f"``{r['model_id']}``", str(r["version"]), r["release"], str(r["terms"]),
             f"{r['rows']:,}", f"{r['positives']:,}",
             f"{r['intercepts']} per {r['unit']}", f"**{_fmt(r['auroc'])}**", r["metric"]]
            for r in summary_rows()]
    body = _list_table(
        "One artifact per ``(cls, species, mode)``, and no fallback",
        ["model", "model version", "release", "terms", "rows", "immunogenic", "intercepts",
         "AUROC", "protocol"],
        rows, widths=[20, 8, 8, 6, 9, 9, 12, 8, 20])
    return "\n".join([_BANNER, ""] + body)


def model_rst(cls, species, mode="neoantigen"):
    """The fit block, the coefficients and whatever held-out record this artifact carries."""
    a = _art(cls, species, mode)
    fit = a.get("fit") or {}
    out = [_BANNER, ""]

    facts = [["rows", f"{fit['rows']:,}"],
             ["immunogenic", f"{fit['positives']:,} ({_pct(fit)})"]]
    for key, label in (("screens", "screens"), ("references", "references"),
                       ("alleles", "allotypes"), ("clusters", "bootstrap clusters")):
        v = fit.get(key)
        if v is not None:
            facts.append([label, f"{len(v)} ({', '.join(v)})" if isinstance(v, list)
                          else f"{v:,}"])
    facts += [["ridge :math:`\\tau`", str(fit.get("tau"))],
              ["bootstrap", f"{fit.get('n_boot')} resamples of "
                            f"{fit.get('bootstrap_unit')}"],
              ["deviance", _fmt(fit.get("deviance"), 1)],
              ["BIC", _fmt(fit.get("bic"), 1)]]
    if "in_sample_auroc" in fit:
        facts.append(["in-sample within-reference AUROC",
                      f"**{_fmt(fit['in_sample_auroc'])}**"])
    if fit.get("holdout"):
        facts.append(["held out", fit["holdout"]])
    facts.append(["corpus block",
                  f"k = {a['corpus_k']}, kernel ``{a['corpus_kernel']}``, "
                  f"mask ``{a['corpus_mask']}``, bandwidths "
                  + ", ".join(f"{c} {k}" for c, k in a["corpus_shapes"].items())
                  if "corpus_k" in a
                  else "not in this design -- the deposited references are class I"])
    out += _list_table("What the fit rests on", None, facts, widths=[34, 66])

    block_of = {t: b for b, terms in a["blocks"] for t in terms}
    rows = []
    for i, t in enumerate(a["features"]):
        lo, hi = _at(a["ci95"], t, i)
        rows.append([f"``{block_of.get(t, '')}``", f"``{t}``",
                     f"**{_at(a['coef'], t, i):+.4f}**",
                     _fmt(_at(a.get("boot_sd"), t, i)),
                     f"{_at(a['z'], t, i):+.2f}", _p(_at(a["p"], t, i)),
                     f":math:`[{lo:+.3f}, {hi:+.3f}]`",
                     _fmt(_at(a.get("sign_stability"), t, i), 2)])
    out += _list_table(
        "Coefficients, standardised -- log-odds per SD of the term's own column",
        ["block", "term", "coef", "boot sd", "z", "p", "95 % CI", "sign stability"],
        rows, widths=[12, 16, 10, 8, 8, 9, 18, 10])

    loo = a.get("loo")
    if loo:
        out += _list_table(
            "Held out one screen at a time, scored on the screen the fit never saw",
            ["screen", "rows", "immunogenic", "AUROC"],
            [[r["level"], f"{r['n']:,}", f"{r['pos']:,}", f"**{_fmt(r['auroc'])}**"]
             for r in loo] +
            [[f"**mean over the {len(loo)}**", "", "",
              f"**{_fmt(sum(r['auroc'] for r in loo) / len(loo))}**"]],
            widths=[20, 12, 12, 12])
    cvs = [(k, a[k]) for k in ("cv_peptide", "cv_twin") if a.get(k)]
    if cvs:
        out += _list_table(
            "Grouped cross-validation, whole groups held out",
            ["grouping", "folds", "groups", "mean over deciding screens",
             "median", "pooled"],
            [[f"``{k}``", str(v["folds"]), f"{v['groups']:,}",
              _fmt(v["mean_decided"]), _fmt(v["median_decided"]),
              _fmt(v["pooled_auroc"])] for k, v in cvs],
            widths=[16, 8, 12, 22, 12, 12])
    return "\n".join(out)


_BANNER = (".. GENERATED by ``mhcmatch._modeldoc`` from the shipped artifacts -- do not edit.\n"
           ".. ``docs/conf.py`` rewrites this file on every build.")


def write(root=None):
    """Refresh ``docs/_generated/`` and the README block. Returns the paths it wrote."""
    root = pathlib.Path(root or pathlib.Path(__file__).resolve().parents[2])
    gen = root / "docs" / "_generated"
    gen.mkdir(parents=True, exist_ok=True)
    written = [gen / "models_summary.rst"]
    written[0].write_text(summary_rst() + "\n")
    for cls, species, mode in ORDER:
        p = gen / f"model_{cls}_{species}_{mode}.rst"
        p.write_text(model_rst(cls, species, mode) + "\n")
        written.append(p)

    readme = root / "README.md"
    if readme.exists():
        txt = readme.read_text()
        if README_BEGIN in txt and README_END in txt:
            head, _, rest = txt.partition(README_BEGIN)
            _, _, tail = rest.partition(README_END)
            readme.write_text(f"{head}{README_BEGIN}\n{readme_markdown()}\n{README_END}{tail}")
            written.append(readme)
    return written


if __name__ == "__main__":  # pragma: no cover
    for p in write():
        print(p)
